[2024-10-07T22:18:12.102-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-07T22:18:12.125-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: preprocess_predict.task_prediction manual__2024-10-08T01:17:46.416729+00:00 [queued]>
[2024-10-07T22:18:12.137-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: preprocess_predict.task_prediction manual__2024-10-08T01:17:46.416729+00:00 [queued]>
[2024-10-07T22:18:12.138-0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-07T22:18:12.154-0300] {taskinstance.py:2330} INFO - Executing <Task(_DockerDecoratedOperator): task_prediction> on 2024-10-08 01:17:46.416729+00:00
[2024-10-07T22:18:12.161-0300] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2469) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-07T22:18:12.163-0300] {standard_task_runner.py:63} INFO - Started process 2470 to run task
[2024-10-07T22:18:12.163-0300] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'preprocess_predict', 'task_prediction', 'manual__2024-10-08T01:17:46.416729+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/Predict/preprocess_predict.py', '--cfg-path', '/tmp/tmpop26rojw']
[2024-10-07T22:18:12.164-0300] {standard_task_runner.py:91} INFO - Job 63: Subtask task_prediction
[2024-10-07T22:18:12.215-0300] {task_command.py:426} INFO - Running <TaskInstance: preprocess_predict.task_prediction manual__2024-10-08T01:17:46.416729+00:00 [running]> on host 4a07270c49a4
[2024-10-07T22:18:12.317-0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='preprocess_predict' AIRFLOW_CTX_TASK_ID='task_prediction' AIRFLOW_CTX_EXECUTION_DATE='2024-10-08T01:17:46.416729+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-08T01:17:46.416729+00:00'
[2024-10-07T22:18:12.318-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-07T22:18:12.321-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-07T22:18:12.322-0300] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/decorators/docker.py", line 102, in execute
    self.pickling_library.dump({"args": self.op_args, "kwargs": self.op_kwargs}, file)
_pickle.PicklingError: Can't pickle <function task_preprocess at 0x7f65e0233880>: it's not the same object as common.add_task.task_preprocess
[2024-10-07T22:18:12.331-0300] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=preprocess_predict, task_id=task_prediction, run_id=manual__2024-10-08T01:17:46.416729+00:00, execution_date=20241008T011746, start_date=20241008T011812, end_date=20241008T011812
[2024-10-07T22:18:12.349-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 63 for task task_prediction (Can't pickle <function task_preprocess at 0x7f65e0233880>: it's not the same object as common.add_task.task_preprocess; 2470)
[2024-10-07T22:18:12.378-0300] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-07T22:18:12.399-0300] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-07T22:18:12.402-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
