[2024-10-08T08:27:16.403-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-08T08:27:16.430-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: preprocess_predict.prediction manual__2024-10-08T11:26:42.227711+00:00 [queued]>
[2024-10-08T08:27:16.441-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: preprocess_predict.prediction manual__2024-10-08T11:26:42.227711+00:00 [queued]>
[2024-10-08T08:27:16.442-0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-08T08:27:16.457-0300] {taskinstance.py:2330} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): prediction> on 2024-10-08 11:26:42.227711+00:00
[2024-10-08T08:27:16.463-0300] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=439) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-08T08:27:16.464-0300] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'preprocess_predict', 'prediction', 'manual__2024-10-08T11:26:42.227711+00:00', '--job-id', '117', '--raw', '--subdir', 'DAGS_FOLDER/Predict/preprocess_predict.py', '--cfg-path', '/tmp/tmpq4605byk']
[2024-10-08T08:27:16.465-0300] {standard_task_runner.py:63} INFO - Started process 440 to run task
[2024-10-08T08:27:16.466-0300] {standard_task_runner.py:91} INFO - Job 117: Subtask prediction
[2024-10-08T08:27:16.519-0300] {task_command.py:426} INFO - Running <TaskInstance: preprocess_predict.prediction manual__2024-10-08T11:26:42.227711+00:00 [running]> on host 4a07270c49a4
[2024-10-08T08:27:16.649-0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='preprocess_predict' AIRFLOW_CTX_TASK_ID='prediction' AIRFLOW_CTX_EXECUTION_DATE='2024-10-08T11:26:42.227711+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-08T11:26:42.227711+00:00'
[2024-10-08T08:27:16.653-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-08T08:27:16.657-0300] {process_utils.py:183} INFO - Executing cmd: /home/***/.local/bin/python -m virtualenv /tmp/venv518k6hj8 --python=python
[2024-10-08T08:27:16.659-0300] {process_utils.py:187} INFO - Output:
[2024-10-08T08:27:17.393-0300] {process_utils.py:191} INFO - created virtual environment CPython3.12.3.final.0-64 in 223ms
[2024-10-08T08:27:17.395-0300] {process_utils.py:191} INFO -   creator CPython3Posix(dest=/tmp/venv518k6hj8, clear=False, no_vcs_ignore=False, global=False)
[2024-10-08T08:27:17.396-0300] {process_utils.py:191} INFO -   seeder FromAppData(download=False, pip=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-10-08T08:27:17.396-0300] {process_utils.py:191} INFO -     added seed packages: pip==24.2
[2024-10-08T08:27:17.397-0300] {process_utils.py:191} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-10-08T08:27:17.440-0300] {process_utils.py:183} INFO - Executing cmd: /tmp/venv518k6hj8/bin/pip install -r /tmp/venv518k6hj8/requirements.txt
[2024-10-08T08:27:17.441-0300] {process_utils.py:187} INFO - Output:
[2024-10-08T08:27:18.971-0300] {process_utils.py:191} INFO - Collecting joblib (from -r /tmp/venv518k6hj8/requirements.txt (line 1))
[2024-10-08T08:27:18.973-0300] {process_utils.py:191} INFO -   Using cached joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
[2024-10-08T08:27:19.203-0300] {process_utils.py:191} INFO - Collecting numpy (from -r /tmp/venv518k6hj8/requirements.txt (line 2))
[2024-10-08T08:27:19.204-0300] {process_utils.py:191} INFO -   Using cached numpy-2.1.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
[2024-10-08T08:27:19.419-0300] {process_utils.py:191} INFO - Collecting pandas (from -r /tmp/venv518k6hj8/requirements.txt (line 3))
[2024-10-08T08:27:19.420-0300] {process_utils.py:191} INFO -   Using cached pandas-2.2.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (89 kB)
[2024-10-08T08:27:19.593-0300] {process_utils.py:191} INFO - Collecting scikit-learn (from -r /tmp/venv518k6hj8/requirements.txt (line 4))
[2024-10-08T08:27:19.595-0300] {process_utils.py:191} INFO -   Using cached scikit_learn-1.5.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (13 kB)
[2024-10-08T08:27:19.660-0300] {process_utils.py:191} INFO - Collecting python-dateutil>=2.8.2 (from pandas->-r /tmp/venv518k6hj8/requirements.txt (line 3))
[2024-10-08T08:27:19.662-0300] {process_utils.py:191} INFO -   Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
[2024-10-08T08:27:19.736-0300] {process_utils.py:191} INFO - Collecting pytz>=2020.1 (from pandas->-r /tmp/venv518k6hj8/requirements.txt (line 3))
[2024-10-08T08:27:19.738-0300] {process_utils.py:191} INFO -   Using cached pytz-2024.2-py2.py3-none-any.whl.metadata (22 kB)
[2024-10-08T08:27:19.767-0300] {process_utils.py:191} INFO - Collecting tzdata>=2022.7 (from pandas->-r /tmp/venv518k6hj8/requirements.txt (line 3))
[2024-10-08T08:27:19.770-0300] {process_utils.py:191} INFO -   Using cached tzdata-2024.2-py2.py3-none-any.whl.metadata (1.4 kB)
[2024-10-08T08:27:19.932-0300] {process_utils.py:191} INFO - Collecting scipy>=1.6.0 (from scikit-learn->-r /tmp/venv518k6hj8/requirements.txt (line 4))
[2024-10-08T08:27:19.935-0300] {process_utils.py:191} INFO -   Using cached scipy-1.14.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
[2024-10-08T08:27:19.979-0300] {process_utils.py:191} INFO - Collecting threadpoolctl>=3.1.0 (from scikit-learn->-r /tmp/venv518k6hj8/requirements.txt (line 4))
[2024-10-08T08:27:19.981-0300] {process_utils.py:191} INFO -   Using cached threadpoolctl-3.5.0-py3-none-any.whl.metadata (13 kB)
[2024-10-08T08:27:20.010-0300] {process_utils.py:191} INFO - Collecting six>=1.5 (from python-dateutil>=2.8.2->pandas->-r /tmp/venv518k6hj8/requirements.txt (line 3))
[2024-10-08T08:27:20.012-0300] {process_utils.py:191} INFO -   Using cached six-1.16.0-py2.py3-none-any.whl.metadata (1.8 kB)
[2024-10-08T08:27:20.030-0300] {process_utils.py:191} INFO - Using cached joblib-1.4.2-py3-none-any.whl (301 kB)
[2024-10-08T08:27:20.034-0300] {process_utils.py:191} INFO - Using cached numpy-2.1.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.0 MB)
[2024-10-08T08:27:20.104-0300] {process_utils.py:191} INFO - Using cached pandas-2.2.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.7 MB)
[2024-10-08T08:27:20.122-0300] {process_utils.py:191} INFO - Using cached scikit_learn-1.5.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.9 MB)
[2024-10-08T08:27:20.139-0300] {process_utils.py:191} INFO - Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
[2024-10-08T08:27:20.141-0300] {process_utils.py:191} INFO - Using cached pytz-2024.2-py2.py3-none-any.whl (508 kB)
[2024-10-08T08:27:20.144-0300] {process_utils.py:191} INFO - Using cached scipy-1.14.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (40.8 MB)
[2024-10-08T08:27:20.198-0300] {process_utils.py:191} INFO - Using cached threadpoolctl-3.5.0-py3-none-any.whl (18 kB)
[2024-10-08T08:27:20.201-0300] {process_utils.py:191} INFO - Using cached tzdata-2024.2-py2.py3-none-any.whl (346 kB)
[2024-10-08T08:27:20.203-0300] {process_utils.py:191} INFO - Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
[2024-10-08T08:27:20.433-0300] {process_utils.py:191} INFO - Installing collected packages: pytz, tzdata, threadpoolctl, six, numpy, joblib, scipy, python-dateutil, scikit-learn, pandas
[2024-10-08T08:27:36.776-0300] {process_utils.py:191} INFO - Successfully installed joblib-1.4.2 numpy-2.1.2 pandas-2.2.3 python-dateutil-2.9.0.post0 pytz-2024.2 scikit-learn-1.5.2 scipy-1.14.1 six-1.16.0 threadpoolctl-3.5.0 tzdata-2024.2
[2024-10-08T08:27:37.208-0300] {process_utils.py:183} INFO - Executing cmd: /tmp/venv518k6hj8/bin/python /tmp/venv-callhcruw5ke/script.py /tmp/venv-callhcruw5ke/script.in /tmp/venv-callhcruw5ke/script.out /tmp/venv-callhcruw5ke/string_args.txt /tmp/venv-callhcruw5ke/termination.log
[2024-10-08T08:27:37.209-0300] {process_utils.py:187} INFO - Output:
[2024-10-08T08:27:39.138-0300] {process_utils.py:191} INFO - Traceback (most recent call last):
[2024-10-08T08:27:39.139-0300] {process_utils.py:191} INFO -   File "/tmp/venv-callhcruw5ke/script.py", line 55, in <module>
[2024-10-08T08:27:39.140-0300] {process_utils.py:191} INFO -     res = task_prediction(*arg_dict["args"], **arg_dict["kwargs"])
[2024-10-08T08:27:39.141-0300] {process_utils.py:191} INFO -           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-10-08T08:27:39.142-0300] {process_utils.py:191} INFO -   File "/tmp/venv-callhcruw5ke/script.py", line 31, in task_prediction
[2024-10-08T08:27:39.143-0300] {process_utils.py:191} INFO -     prediction=regressor.predict(X_test)
[2024-10-08T08:27:39.144-0300] {process_utils.py:191} INFO -                ^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-10-08T08:27:39.145-0300] {process_utils.py:191} INFO -   File "/tmp/venv518k6hj8/lib/python3.12/site-packages/sklearn/ensemble/_forest.py", line 1063, in predict
[2024-10-08T08:27:39.146-0300] {process_utils.py:191} INFO -     X = self._validate_X_predict(X)
[2024-10-08T08:27:39.147-0300] {process_utils.py:191} INFO -         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-10-08T08:27:39.148-0300] {process_utils.py:191} INFO -   File "/tmp/venv518k6hj8/lib/python3.12/site-packages/sklearn/ensemble/_forest.py", line 641, in _validate_X_predict
[2024-10-08T08:27:39.148-0300] {process_utils.py:191} INFO -     X = self._validate_data(
[2024-10-08T08:27:39.150-0300] {process_utils.py:191} INFO -         ^^^^^^^^^^^^^^^^^^^^
[2024-10-08T08:27:39.151-0300] {process_utils.py:191} INFO -   File "/tmp/venv518k6hj8/lib/python3.12/site-packages/sklearn/base.py", line 608, in _validate_data
[2024-10-08T08:27:39.152-0300] {process_utils.py:191} INFO -     self._check_feature_names(X, reset=reset)
[2024-10-08T08:27:39.153-0300] {process_utils.py:191} INFO -   File "/tmp/venv518k6hj8/lib/python3.12/site-packages/sklearn/base.py", line 535, in _check_feature_names
[2024-10-08T08:27:39.154-0300] {process_utils.py:191} INFO -     raise ValueError(message)
[2024-10-08T08:27:39.154-0300] {process_utils.py:191} INFO - ValueError: The feature names should match those that were passed during fit.
[2024-10-08T08:27:39.155-0300] {process_utils.py:191} INFO - Feature names seen at fit time, yet now missing:
[2024-10-08T08:27:39.156-0300] {process_utils.py:191} INFO - - color_beige
[2024-10-08T08:27:39.157-0300] {process_utils.py:191} INFO - - color_blue
[2024-10-08T08:27:39.158-0300] {process_utils.py:191} INFO - - color_brown
[2024-10-08T08:27:39.159-0300] {process_utils.py:191} INFO - - color_cherry
[2024-10-08T08:27:39.160-0300] {process_utils.py:191} INFO - - color_clove
[2024-10-08T08:27:39.160-0300] {process_utils.py:191} INFO - - ...
[2024-10-08T08:27:39.161-0300] {process_utils.py:191} INFO - 
[2024-10-08T08:27:39.652-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-08T08:27:39.666-0300] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 437, in execute
    return super().execute(context=serializable_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 759, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 514, in _execute_python_callable_in_subprocess
    raise AirflowException(error_msg) from None
airflow.exceptions.AirflowException: Process returned non-zero exit status 1.
The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- color_beige
- color_blue
- color_brown
- color_cherry
- color_clove
- ...

[2024-10-08T08:27:39.673-0300] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=preprocess_predict, task_id=prediction, run_id=manual__2024-10-08T11:26:42.227711+00:00, execution_date=20241008T112642, start_date=20241008T112716, end_date=20241008T112739
[2024-10-08T08:27:39.695-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 117 for task prediction (Process returned non-zero exit status 1.
The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- color_beige
- color_blue
- color_brown
- color_cherry
- color_clove
- ...
; 440)
[2024-10-08T08:27:39.734-0300] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-08T08:27:39.751-0300] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-08T08:27:39.754-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
