[2024-10-07T21:12:08.884-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-07T21:12:08.908-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: preprocess_predict.preprocessvalues manual__2024-10-08T00:12:07.269872+00:00 [queued]>
[2024-10-07T21:12:08.919-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: preprocess_predict.preprocessvalues manual__2024-10-08T00:12:07.269872+00:00 [queued]>
[2024-10-07T21:12:08.921-0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-10-07T21:12:08.937-0300] {taskinstance.py:2330} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): preprocessvalues> on 2024-10-08 00:12:07.269872+00:00
[2024-10-07T21:12:08.944-0300] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=197) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-07T21:12:08.946-0300] {standard_task_runner.py:63} INFO - Started process 198 to run task
[2024-10-07T21:12:08.945-0300] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'preprocess_predict', 'preprocessvalues', 'manual__2024-10-08T00:12:07.269872+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/Predict/preprocess_predict.py', '--cfg-path', '/tmp/tmpuaiam0n5']
[2024-10-07T21:12:08.947-0300] {standard_task_runner.py:91} INFO - Job 18: Subtask preprocessvalues
[2024-10-07T21:12:08.992-0300] {task_command.py:426} INFO - Running <TaskInstance: preprocess_predict.preprocessvalues manual__2024-10-08T00:12:07.269872+00:00 [running]> on host 4a07270c49a4
[2024-10-07T21:12:09.078-0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='preprocess_predict' AIRFLOW_CTX_TASK_ID='preprocessvalues' AIRFLOW_CTX_EXECUTION_DATE='2024-10-08T00:12:07.269872+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-08T00:12:07.269872+00:00'
[2024-10-07T21:12:09.079-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-07T21:12:09.081-0300] {process_utils.py:183} INFO - Executing cmd: /home/***/.local/bin/python -m virtualenv /tmp/venvk_nan5uc --python=python
[2024-10-07T21:12:09.082-0300] {process_utils.py:187} INFO - Output:
[2024-10-07T21:12:09.699-0300] {process_utils.py:191} INFO - created virtual environment CPython3.12.3.final.0-64 in 198ms
[2024-10-07T21:12:09.700-0300] {process_utils.py:191} INFO -   creator CPython3Posix(dest=/tmp/venvk_nan5uc, clear=False, no_vcs_ignore=False, global=False)
[2024-10-07T21:12:09.701-0300] {process_utils.py:191} INFO -   seeder FromAppData(download=False, pip=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-10-07T21:12:09.702-0300] {process_utils.py:191} INFO -     added seed packages: pip==24.2
[2024-10-07T21:12:09.703-0300] {process_utils.py:191} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-10-07T21:12:09.746-0300] {process_utils.py:183} INFO - Executing cmd: /tmp/venvk_nan5uc/bin/pip install -r /tmp/venvk_nan5uc/requirements.txt
[2024-10-07T21:12:09.747-0300] {process_utils.py:187} INFO - Output:
[2024-10-07T21:12:11.065-0300] {process_utils.py:191} INFO - Collecting joblib (from -r /tmp/venvk_nan5uc/requirements.txt (line 1))
[2024-10-07T21:12:11.067-0300] {process_utils.py:191} INFO -   Using cached joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
[2024-10-07T21:12:11.275-0300] {process_utils.py:191} INFO - Collecting numpy (from -r /tmp/venvk_nan5uc/requirements.txt (line 2))
[2024-10-07T21:12:11.277-0300] {process_utils.py:191} INFO -   Using cached numpy-2.1.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
[2024-10-07T21:12:11.498-0300] {process_utils.py:191} INFO - Collecting pandas (from -r /tmp/venvk_nan5uc/requirements.txt (line 3))
[2024-10-07T21:12:11.500-0300] {process_utils.py:191} INFO -   Using cached pandas-2.2.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (89 kB)
[2024-10-07T21:12:11.661-0300] {process_utils.py:191} INFO - Collecting scikit-learn (from -r /tmp/venvk_nan5uc/requirements.txt (line 4))
[2024-10-07T21:12:11.662-0300] {process_utils.py:191} INFO -   Using cached scikit_learn-1.5.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (13 kB)
[2024-10-07T21:12:11.709-0300] {process_utils.py:191} INFO - Collecting python-dateutil>=2.8.2 (from pandas->-r /tmp/venvk_nan5uc/requirements.txt (line 3))
[2024-10-07T21:12:11.710-0300] {process_utils.py:191} INFO -   Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
[2024-10-07T21:12:11.786-0300] {process_utils.py:191} INFO - Collecting pytz>=2020.1 (from pandas->-r /tmp/venvk_nan5uc/requirements.txt (line 3))
[2024-10-07T21:12:11.788-0300] {process_utils.py:191} INFO -   Using cached pytz-2024.2-py2.py3-none-any.whl.metadata (22 kB)
[2024-10-07T21:12:11.821-0300] {process_utils.py:191} INFO - Collecting tzdata>=2022.7 (from pandas->-r /tmp/venvk_nan5uc/requirements.txt (line 3))
[2024-10-07T21:12:11.823-0300] {process_utils.py:191} INFO -   Using cached tzdata-2024.2-py2.py3-none-any.whl.metadata (1.4 kB)
[2024-10-07T21:12:11.969-0300] {process_utils.py:191} INFO - Collecting scipy>=1.6.0 (from scikit-learn->-r /tmp/venvk_nan5uc/requirements.txt (line 4))
[2024-10-07T21:12:11.970-0300] {process_utils.py:191} INFO -   Using cached scipy-1.14.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
[2024-10-07T21:12:12.012-0300] {process_utils.py:191} INFO - Collecting threadpoolctl>=3.1.0 (from scikit-learn->-r /tmp/venvk_nan5uc/requirements.txt (line 4))
[2024-10-07T21:12:12.014-0300] {process_utils.py:191} INFO -   Using cached threadpoolctl-3.5.0-py3-none-any.whl.metadata (13 kB)
[2024-10-07T21:12:12.042-0300] {process_utils.py:191} INFO - Collecting six>=1.5 (from python-dateutil>=2.8.2->pandas->-r /tmp/venvk_nan5uc/requirements.txt (line 3))
[2024-10-07T21:12:12.043-0300] {process_utils.py:191} INFO -   Using cached six-1.16.0-py2.py3-none-any.whl.metadata (1.8 kB)
[2024-10-07T21:12:12.057-0300] {process_utils.py:191} INFO - Using cached joblib-1.4.2-py3-none-any.whl (301 kB)
[2024-10-07T21:12:12.059-0300] {process_utils.py:191} INFO - Using cached numpy-2.1.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.0 MB)
[2024-10-07T21:12:12.075-0300] {process_utils.py:191} INFO - Using cached pandas-2.2.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.7 MB)
[2024-10-07T21:12:12.087-0300] {process_utils.py:191} INFO - Using cached scikit_learn-1.5.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.9 MB)
[2024-10-07T21:12:12.100-0300] {process_utils.py:191} INFO - Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
[2024-10-07T21:12:12.101-0300] {process_utils.py:191} INFO - Using cached pytz-2024.2-py2.py3-none-any.whl (508 kB)
[2024-10-07T21:12:12.103-0300] {process_utils.py:191} INFO - Using cached scipy-1.14.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (40.8 MB)
[2024-10-07T21:12:12.139-0300] {process_utils.py:191} INFO - Using cached threadpoolctl-3.5.0-py3-none-any.whl (18 kB)
[2024-10-07T21:12:12.140-0300] {process_utils.py:191} INFO - Using cached tzdata-2024.2-py2.py3-none-any.whl (346 kB)
[2024-10-07T21:12:12.141-0300] {process_utils.py:191} INFO - Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
[2024-10-07T21:12:12.328-0300] {process_utils.py:191} INFO - Installing collected packages: pytz, tzdata, threadpoolctl, six, numpy, joblib, scipy, python-dateutil, scikit-learn, pandas
[2024-10-07T21:12:25.996-0300] {process_utils.py:191} INFO - Successfully installed joblib-1.4.2 numpy-2.1.2 pandas-2.2.3 python-dateutil-2.9.0.post0 pytz-2024.2 scikit-learn-1.5.2 scipy-1.14.1 six-1.16.0 threadpoolctl-3.5.0 tzdata-2024.2
[2024-10-07T21:12:26.364-0300] {process_utils.py:183} INFO - Executing cmd: /tmp/venvk_nan5uc/bin/python /tmp/venv-callv6ipkfcl/script.py /tmp/venv-callv6ipkfcl/script.in /tmp/venv-callv6ipkfcl/script.out /tmp/venv-callv6ipkfcl/string_args.txt /tmp/venv-callv6ipkfcl/termination.log
[2024-10-07T21:12:26.365-0300] {process_utils.py:187} INFO - Output:
[2024-10-07T21:12:27.638-0300] {process_utils.py:191} INFO - Traceback (most recent call last):
[2024-10-07T21:12:27.639-0300] {process_utils.py:191} INFO -   File "/tmp/venv-callv6ipkfcl/script.py", line 62, in <module>
[2024-10-07T21:12:27.639-0300] {process_utils.py:191} INFO -     res = task_preprocess(*arg_dict["args"], **arg_dict["kwargs"])
[2024-10-07T21:12:27.640-0300] {process_utils.py:191} INFO -           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-10-07T21:12:27.640-0300] {process_utils.py:191} INFO -   File "/tmp/venv-callv6ipkfcl/script.py", line 24, in task_preprocess
[2024-10-07T21:12:27.641-0300] {process_utils.py:191} INFO -     df = pd.read_csv('/opt/***/dags/data/input/test.csv')
[2024-10-07T21:12:27.642-0300] {process_utils.py:191} INFO -          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-10-07T21:12:27.642-0300] {process_utils.py:191} INFO -   File "/tmp/venvk_nan5uc/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
[2024-10-07T21:12:27.643-0300] {process_utils.py:191} INFO -     return _read(filepath_or_buffer, kwds)
[2024-10-07T21:12:27.643-0300] {process_utils.py:191} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-10-07T21:12:27.644-0300] {process_utils.py:191} INFO -   File "/tmp/venvk_nan5uc/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 620, in _read
[2024-10-07T21:12:27.644-0300] {process_utils.py:191} INFO -     parser = TextFileReader(filepath_or_buffer, **kwds)
[2024-10-07T21:12:27.645-0300] {process_utils.py:191} INFO -              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-10-07T21:12:27.645-0300] {process_utils.py:191} INFO -   File "/tmp/venvk_nan5uc/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
[2024-10-07T21:12:27.646-0300] {process_utils.py:191} INFO -     self._engine = self._make_engine(f, self.engine)
[2024-10-07T21:12:27.646-0300] {process_utils.py:191} INFO -                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-10-07T21:12:27.647-0300] {process_utils.py:191} INFO -   File "/tmp/venvk_nan5uc/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
[2024-10-07T21:12:27.647-0300] {process_utils.py:191} INFO -     self.handles = get_handle(
[2024-10-07T21:12:27.647-0300] {process_utils.py:191} INFO -                    ^^^^^^^^^^^
[2024-10-07T21:12:27.648-0300] {process_utils.py:191} INFO -   File "/tmp/venvk_nan5uc/lib/python3.12/site-packages/pandas/io/common.py", line 873, in get_handle
[2024-10-07T21:12:27.648-0300] {process_utils.py:191} INFO -     handle = open(
[2024-10-07T21:12:27.649-0300] {process_utils.py:191} INFO -              ^^^^^
[2024-10-07T21:12:27.649-0300] {process_utils.py:191} INFO - FileNotFoundError: [Errno 2] No such file or directory: '/opt/***/dags/data/input/test.csv'
[2024-10-07T21:12:28.036-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-07T21:12:28.045-0300] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 437, in execute
    return super().execute(context=serializable_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 759, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 514, in _execute_python_callable_in_subprocess
    raise AirflowException(error_msg) from None
airflow.exceptions.AirflowException: Process returned non-zero exit status 1.
[Errno 2] No such file or directory: '/opt/***/dags/data/input/test.csv'
[2024-10-07T21:12:28.052-0300] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=preprocess_predict, task_id=preprocessvalues, run_id=manual__2024-10-08T00:12:07.269872+00:00, execution_date=20241008T001207, start_date=20241008T001208, end_date=20241008T001228
[2024-10-07T21:12:28.066-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 18 for task preprocessvalues (Process returned non-zero exit status 1.
[Errno 2] No such file or directory: '/opt/***/dags/data/input/test.csv'; 198)
[2024-10-07T21:12:28.087-0300] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-07T21:12:28.109-0300] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-07T21:12:28.112-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
