[2024-10-07T23:59:53.900-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-07T23:59:53.924-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: preprocess_predict.preprocess manual__2024-10-08T02:59:52.420367+00:00 [queued]>
[2024-10-07T23:59:53.934-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: preprocess_predict.preprocess manual__2024-10-08T02:59:52.420367+00:00 [queued]>
[2024-10-07T23:59:53.935-0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-07T23:59:53.951-0300] {taskinstance.py:2330} INFO - Executing <Task(PythonVirtualenvOperator): preprocess> on 2024-10-08 02:59:52.420367+00:00
[2024-10-07T23:59:53.957-0300] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=438) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-07T23:59:53.959-0300] {standard_task_runner.py:63} INFO - Started process 439 to run task
[2024-10-07T23:59:53.959-0300] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'preprocess_predict', 'preprocess', 'manual__2024-10-08T02:59:52.420367+00:00', '--job-id', '103', '--raw', '--subdir', 'DAGS_FOLDER/Predict/preprocess_predict.py', '--cfg-path', '/tmp/tmp4vxr6h48']
[2024-10-07T23:59:53.960-0300] {standard_task_runner.py:91} INFO - Job 103: Subtask preprocess
[2024-10-07T23:59:54.003-0300] {task_command.py:426} INFO - Running <TaskInstance: preprocess_predict.preprocess manual__2024-10-08T02:59:52.420367+00:00 [running]> on host 4a07270c49a4
[2024-10-07T23:59:54.096-0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='preprocess_predict' AIRFLOW_CTX_TASK_ID='preprocess' AIRFLOW_CTX_EXECUTION_DATE='2024-10-08T02:59:52.420367+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-08T02:59:52.420367+00:00'
[2024-10-07T23:59:54.097-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-07T23:59:54.098-0300] {baseoperator.py:399} WARNING - PythonVirtualenvOperator.execute cannot be called outside TaskInstance!
[2024-10-07T23:59:54.099-0300] {process_utils.py:183} INFO - Executing cmd: /home/***/.local/bin/python -m virtualenv /tmp/venvyhig_uny --python=python
[2024-10-07T23:59:54.101-0300] {process_utils.py:187} INFO - Output:
[2024-10-07T23:59:54.816-0300] {process_utils.py:191} INFO - created virtual environment CPython3.12.3.final.0-64 in 240ms
[2024-10-07T23:59:54.817-0300] {process_utils.py:191} INFO -   creator CPython3Posix(dest=/tmp/venvyhig_uny, clear=False, no_vcs_ignore=False, global=False)
[2024-10-07T23:59:54.817-0300] {process_utils.py:191} INFO -   seeder FromAppData(download=False, pip=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-10-07T23:59:54.818-0300] {process_utils.py:191} INFO -     added seed packages: pip==24.2
[2024-10-07T23:59:54.819-0300] {process_utils.py:191} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-10-07T23:59:54.859-0300] {process_utils.py:183} INFO - Executing cmd: /tmp/venvyhig_uny/bin/pip install -r /tmp/venvyhig_uny/requirements.txt
[2024-10-07T23:59:54.861-0300] {process_utils.py:187} INFO - Output:
[2024-10-07T23:59:56.316-0300] {process_utils.py:191} INFO - Collecting joblib (from -r /tmp/venvyhig_uny/requirements.txt (line 1))
[2024-10-07T23:59:56.318-0300] {process_utils.py:191} INFO -   Using cached joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
[2024-10-07T23:59:56.535-0300] {process_utils.py:191} INFO - Collecting numpy (from -r /tmp/venvyhig_uny/requirements.txt (line 2))
[2024-10-07T23:59:56.536-0300] {process_utils.py:191} INFO -   Using cached numpy-2.1.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
[2024-10-07T23:59:56.745-0300] {process_utils.py:191} INFO - Collecting pandas (from -r /tmp/venvyhig_uny/requirements.txt (line 3))
[2024-10-07T23:59:56.747-0300] {process_utils.py:191} INFO -   Using cached pandas-2.2.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (89 kB)
[2024-10-07T23:59:56.906-0300] {process_utils.py:191} INFO - Collecting scikit-learn (from -r /tmp/venvyhig_uny/requirements.txt (line 4))
[2024-10-07T23:59:56.908-0300] {process_utils.py:191} INFO -   Using cached scikit_learn-1.5.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (13 kB)
[2024-10-07T23:59:56.953-0300] {process_utils.py:191} INFO - Collecting python-dateutil>=2.8.2 (from pandas->-r /tmp/venvyhig_uny/requirements.txt (line 3))
[2024-10-07T23:59:56.954-0300] {process_utils.py:191} INFO -   Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
[2024-10-07T23:59:57.021-0300] {process_utils.py:191} INFO - Collecting pytz>=2020.1 (from pandas->-r /tmp/venvyhig_uny/requirements.txt (line 3))
[2024-10-07T23:59:57.023-0300] {process_utils.py:191} INFO -   Using cached pytz-2024.2-py2.py3-none-any.whl.metadata (22 kB)
[2024-10-07T23:59:57.057-0300] {process_utils.py:191} INFO - Collecting tzdata>=2022.7 (from pandas->-r /tmp/venvyhig_uny/requirements.txt (line 3))
[2024-10-07T23:59:57.060-0300] {process_utils.py:191} INFO -   Using cached tzdata-2024.2-py2.py3-none-any.whl.metadata (1.4 kB)
[2024-10-07T23:59:57.216-0300] {process_utils.py:191} INFO - Collecting scipy>=1.6.0 (from scikit-learn->-r /tmp/venvyhig_uny/requirements.txt (line 4))
[2024-10-07T23:59:57.217-0300] {process_utils.py:191} INFO -   Using cached scipy-1.14.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
[2024-10-07T23:59:57.260-0300] {process_utils.py:191} INFO - Collecting threadpoolctl>=3.1.0 (from scikit-learn->-r /tmp/venvyhig_uny/requirements.txt (line 4))
[2024-10-07T23:59:57.261-0300] {process_utils.py:191} INFO -   Using cached threadpoolctl-3.5.0-py3-none-any.whl.metadata (13 kB)
[2024-10-07T23:59:57.286-0300] {process_utils.py:191} INFO - Collecting six>=1.5 (from python-dateutil>=2.8.2->pandas->-r /tmp/venvyhig_uny/requirements.txt (line 3))
[2024-10-07T23:59:57.288-0300] {process_utils.py:191} INFO -   Using cached six-1.16.0-py2.py3-none-any.whl.metadata (1.8 kB)
[2024-10-07T23:59:57.302-0300] {process_utils.py:191} INFO - Using cached joblib-1.4.2-py3-none-any.whl (301 kB)
[2024-10-07T23:59:57.304-0300] {process_utils.py:191} INFO - Using cached numpy-2.1.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.0 MB)
[2024-10-07T23:59:57.325-0300] {process_utils.py:191} INFO - Using cached pandas-2.2.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.7 MB)
[2024-10-07T23:59:57.342-0300] {process_utils.py:191} INFO - Using cached scikit_learn-1.5.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.9 MB)
[2024-10-07T23:59:57.360-0300] {process_utils.py:191} INFO - Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
[2024-10-07T23:59:57.362-0300] {process_utils.py:191} INFO - Using cached pytz-2024.2-py2.py3-none-any.whl (508 kB)
[2024-10-07T23:59:57.364-0300] {process_utils.py:191} INFO - Using cached scipy-1.14.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (40.8 MB)
[2024-10-07T23:59:57.427-0300] {process_utils.py:191} INFO - Using cached threadpoolctl-3.5.0-py3-none-any.whl (18 kB)
[2024-10-07T23:59:57.429-0300] {process_utils.py:191} INFO - Using cached tzdata-2024.2-py2.py3-none-any.whl (346 kB)
[2024-10-07T23:59:57.432-0300] {process_utils.py:191} INFO - Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
[2024-10-07T23:59:57.636-0300] {process_utils.py:191} INFO - Installing collected packages: pytz, tzdata, threadpoolctl, six, numpy, joblib, scipy, python-dateutil, scikit-learn, pandas
[2024-10-08T00:00:12.231-0300] {process_utils.py:191} INFO - Successfully installed joblib-1.4.2 numpy-2.1.2 pandas-2.2.3 python-dateutil-2.9.0.post0 pytz-2024.2 scikit-learn-1.5.2 scipy-1.14.1 six-1.16.0 threadpoolctl-3.5.0 tzdata-2024.2
[2024-10-08T00:00:12.655-0300] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:212: AirflowContextDeprecationWarning: Accessing 'next_ds' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-10-08T00:00:12.656-0300] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:212: AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-10-08T00:00:12.657-0300] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:212: AirflowContextDeprecationWarning: Accessing 'prev_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-10-08T00:00:12.658-0300] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:212: AirflowContextDeprecationWarning: Accessing 'prev_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-10-08T00:00:12.659-0300] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:212: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-10-08T00:00:12.659-0300] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:212: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-10-08T00:00:12.660-0300] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:212: AirflowContextDeprecationWarning: Accessing 'yesterday_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-10-08T00:00:12.661-0300] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:212: AirflowContextDeprecationWarning: Accessing 'yesterday_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-10-08T00:00:12.682-0300] {process_utils.py:183} INFO - Executing cmd: /tmp/venvyhig_uny/bin/python /tmp/venv-callptd45yvx/script.py /tmp/venv-callptd45yvx/script.in /tmp/venv-callptd45yvx/script.out /tmp/venv-callptd45yvx/string_args.txt /tmp/venv-callptd45yvx/termination.log
[2024-10-08T00:00:12.684-0300] {process_utils.py:187} INFO - Output:
[2024-10-08T00:00:14.223-0300] {process_utils.py:191} INFO - hola
[2024-10-08T00:00:14.224-0300] {process_utils.py:191} INFO - {'ds': '2024-10-08', 'ds_nodash': '20241008', 'expanded_ti_count': None, 'inlets': [], 'map_index_template': None, 'next_ds': '2024-10-08', 'next_ds_nodash': '20241008', 'outlets': [], 'prev_ds': '2024-10-08', 'prev_ds_nodash': '20241008', 'run_id': 'manual__2024-10-08T02:59:52.420367+00:00', 'task_instance_key_str': 'preprocess_predict__preprocess__20241008', 'test_mode': False, 'tomorrow_ds': '2024-10-09', 'tomorrow_ds_nodash': '20241009', 'ts': '2024-10-08T02:59:52.420367+00:00', 'ts_nodash': '20241008T025952', 'ts_nodash_with_tz': '20241008T025952.420367+0000', 'yesterday_ds': '2024-10-07', 'yesterday_ds_nodash': '20241007', 'templates_dict': None}
[2024-10-08T00:00:14.224-0300] {process_utils.py:191} INFO - chao
[2024-10-08T00:00:14.225-0300] {process_utils.py:191} INFO - Traceback (most recent call last):
[2024-10-08T00:00:14.226-0300] {process_utils.py:191} INFO -   File "/tmp/venv-callptd45yvx/script.py", line 78, in <module>
[2024-10-08T00:00:14.226-0300] {process_utils.py:191} INFO -     res = task_preprocess(*arg_dict["args"], **arg_dict["kwargs"])
[2024-10-08T00:00:14.227-0300] {process_utils.py:191} INFO -           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-10-08T00:00:14.228-0300] {process_utils.py:191} INFO -   File "/tmp/venv-callptd45yvx/script.py", line 25, in task_preprocess
[2024-10-08T00:00:14.228-0300] {process_utils.py:191} INFO -     ti = kwargs['ti']
[2024-10-08T00:00:14.229-0300] {process_utils.py:191} INFO -          ~~~~~~^^^^^^
[2024-10-08T00:00:14.229-0300] {process_utils.py:191} INFO - KeyError: 'ti'
[2024-10-08T00:00:14.676-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-08T00:00:14.692-0300] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 437, in execute
    return super().execute(context=serializable_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 759, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 514, in _execute_python_callable_in_subprocess
    raise AirflowException(error_msg) from None
airflow.exceptions.AirflowException: Process returned non-zero exit status 1.
'ti'
[2024-10-08T00:00:14.708-0300] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=preprocess_predict, task_id=preprocess, run_id=manual__2024-10-08T02:59:52.420367+00:00, execution_date=20241008T025952, start_date=20241008T025953, end_date=20241008T030014
[2024-10-08T00:00:14.725-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 103 for task preprocess (Process returned non-zero exit status 1.
'ti'; 439)
[2024-10-08T00:00:14.741-0300] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-08T00:00:14.767-0300] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-08T00:00:14.777-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
