[2024-10-08T00:19:01.209-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-08T00:19:01.237-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: preprocess_predict.preprocess manual__2024-10-08T03:18:59.580621+00:00 [queued]>
[2024-10-08T00:19:01.247-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: preprocess_predict.preprocess manual__2024-10-08T03:18:59.580621+00:00 [queued]>
[2024-10-08T00:19:01.248-0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-08T00:19:01.263-0300] {taskinstance.py:2330} INFO - Executing <Task(_DockerDecoratedOperator): preprocess> on 2024-10-08 03:18:59.580621+00:00
[2024-10-08T00:19:01.268-0300] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=121) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-08T00:19:01.270-0300] {standard_task_runner.py:63} INFO - Started process 122 to run task
[2024-10-08T00:19:01.270-0300] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'preprocess_predict', 'preprocess', 'manual__2024-10-08T03:18:59.580621+00:00', '--job-id', '109', '--raw', '--subdir', 'DAGS_FOLDER/Predict/preprocess_predict.py', '--cfg-path', '/tmp/tmpri6fgrda']
[2024-10-08T00:19:01.272-0300] {standard_task_runner.py:91} INFO - Job 109: Subtask preprocess
[2024-10-08T00:19:01.316-0300] {task_command.py:426} INFO - Running <TaskInstance: preprocess_predict.preprocess manual__2024-10-08T03:18:59.580621+00:00 [running]> on host 4a07270c49a4
[2024-10-08T00:19:01.408-0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='preprocess_predict' AIRFLOW_CTX_TASK_ID='preprocess' AIRFLOW_CTX_EXECUTION_DATE='2024-10-08T03:18:59.580621+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-08T03:18:59.580621+00:00'
[2024-10-08T00:19:01.410-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-08T00:19:01.411-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-08T00:19:01.412-0300] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/decorators/docker.py", line 102, in execute
    self.pickling_library.dump({"args": self.op_args, "kwargs": self.op_kwargs}, file)
_pickle.PicklingError: Can't pickle <function task_preprocess at 0x7f4f188aa8e0>: it's not the same object as common.add_task.task_preprocess
[2024-10-08T00:19:01.422-0300] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=preprocess_predict, task_id=preprocess, run_id=manual__2024-10-08T03:18:59.580621+00:00, execution_date=20241008T031859, start_date=20241008T031901, end_date=20241008T031901
[2024-10-08T00:19:01.436-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 109 for task preprocess (Can't pickle <function task_preprocess at 0x7f4f188aa8e0>: it's not the same object as common.add_task.task_preprocess; 122)
[2024-10-08T00:19:01.445-0300] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-08T00:19:01.470-0300] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-08T00:19:01.476-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
