[2024-10-07T23:27:09.622-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-07T23:27:09.665-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: preprocess_predict.preprocess manual__2024-10-08T02:27:07.579164+00:00 [queued]>
[2024-10-07T23:27:09.682-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: preprocess_predict.preprocess manual__2024-10-08T02:27:07.579164+00:00 [queued]>
[2024-10-07T23:27:09.684-0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-07T23:27:09.710-0300] {taskinstance.py:2330} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): preprocess> on 2024-10-08 02:27:07.579164+00:00
[2024-10-07T23:27:09.718-0300] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=4056) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-07T23:27:09.721-0300] {standard_task_runner.py:63} INFO - Started process 4057 to run task
[2024-10-07T23:27:09.721-0300] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'preprocess_predict', 'preprocess', 'manual__2024-10-08T02:27:07.579164+00:00', '--job-id', '90', '--raw', '--subdir', 'DAGS_FOLDER/Predict/preprocess_predict.py', '--cfg-path', '/tmp/tmpd4fkx9n8']
[2024-10-07T23:27:09.723-0300] {standard_task_runner.py:91} INFO - Job 90: Subtask preprocess
[2024-10-07T23:27:09.802-0300] {task_command.py:426} INFO - Running <TaskInstance: preprocess_predict.preprocess manual__2024-10-08T02:27:07.579164+00:00 [running]> on host 4a07270c49a4
[2024-10-07T23:27:09.985-0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='preprocess_predict' AIRFLOW_CTX_TASK_ID='preprocess' AIRFLOW_CTX_EXECUTION_DATE='2024-10-08T02:27:07.579164+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-08T02:27:07.579164+00:00'
[2024-10-07T23:27:09.987-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-07T23:27:09.990-0300] {process_utils.py:183} INFO - Executing cmd: /home/***/.local/bin/python -m virtualenv /tmp/venv_z5q5wuc --python=python
[2024-10-07T23:27:09.992-0300] {process_utils.py:187} INFO - Output:
[2024-10-07T23:27:11.432-0300] {process_utils.py:191} INFO - created virtual environment CPython3.12.3.final.0-64 in 395ms
[2024-10-07T23:27:11.434-0300] {process_utils.py:191} INFO -   creator CPython3Posix(dest=/tmp/venv_z5q5wuc, clear=False, no_vcs_ignore=False, global=False)
[2024-10-07T23:27:11.436-0300] {process_utils.py:191} INFO -   seeder FromAppData(download=False, pip=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-10-07T23:27:11.438-0300] {process_utils.py:191} INFO -     added seed packages: pip==24.2
[2024-10-07T23:27:11.439-0300] {process_utils.py:191} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-10-07T23:27:11.489-0300] {process_utils.py:183} INFO - Executing cmd: /tmp/venv_z5q5wuc/bin/pip install -r /tmp/venv_z5q5wuc/requirements.txt
[2024-10-07T23:27:11.491-0300] {process_utils.py:187} INFO - Output:
[2024-10-07T23:27:13.835-0300] {process_utils.py:191} INFO - Collecting joblib (from -r /tmp/venv_z5q5wuc/requirements.txt (line 1))
[2024-10-07T23:27:13.838-0300] {process_utils.py:191} INFO -   Using cached joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
[2024-10-07T23:27:13.973-0300] {process_utils.py:191} INFO - ERROR: Could not find a version that satisfies the requirement json (from versions: none)
[2024-10-07T23:27:14.143-0300] {process_utils.py:191} INFO - ERROR: No matching distribution found for json
[2024-10-07T23:27:14.266-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-07T23:27:14.268-0300] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 437, in execute
    return super().execute(context=serializable_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 757, in execute_callable
    self._prepare_venv(tmp_path)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 669, in _prepare_venv
    prepare_virtualenv(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/python_virtualenv.py", line 119, in prepare_virtualenv
    execute_in_subprocess(pip_cmd)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/process_utils.py", line 172, in execute_in_subprocess
    execute_in_subprocess_with_kwargs(cmd, cwd=cwd)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/process_utils.py", line 195, in execute_in_subprocess_with_kwargs
    raise subprocess.CalledProcessError(exit_code, cmd)
subprocess.CalledProcessError: Command '['/tmp/venv_z5q5wuc/bin/pip', 'install', '-r', '/tmp/venv_z5q5wuc/requirements.txt']' returned non-zero exit status 1.
[2024-10-07T23:27:14.279-0300] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=preprocess_predict, task_id=preprocess, run_id=manual__2024-10-08T02:27:07.579164+00:00, execution_date=20241008T022707, start_date=20241008T022709, end_date=20241008T022714
[2024-10-07T23:27:14.306-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 90 for task preprocess (Command '['/tmp/venv_z5q5wuc/bin/pip', 'install', '-r', '/tmp/venv_z5q5wuc/requirements.txt']' returned non-zero exit status 1.; 4057)
[2024-10-07T23:27:14.320-0300] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-07T23:27:14.343-0300] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-07T23:27:14.348-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
