[2024-10-07T23:36:36.328-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-07T23:36:36.375-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: preprocess_predict.preprocess manual__2024-10-08T02:36:35.215499+00:00 [queued]>
[2024-10-07T23:36:36.392-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: preprocess_predict.preprocess manual__2024-10-08T02:36:35.215499+00:00 [queued]>
[2024-10-07T23:36:36.393-0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-07T23:36:36.414-0300] {taskinstance.py:2330} INFO - Executing <Task(PythonVirtualenvOperator): preprocess> on 2024-10-08 02:36:35.215499+00:00
[2024-10-07T23:36:36.427-0300] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=4258) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-07T23:36:36.429-0300] {standard_task_runner.py:63} INFO - Started process 4259 to run task
[2024-10-07T23:36:36.429-0300] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'preprocess_predict', 'preprocess', 'manual__2024-10-08T02:36:35.215499+00:00', '--job-id', '94', '--raw', '--subdir', 'DAGS_FOLDER/Predict/preprocess_predict.py', '--cfg-path', '/tmp/tmpb__1krf7']
[2024-10-07T23:36:36.431-0300] {standard_task_runner.py:91} INFO - Job 94: Subtask preprocess
[2024-10-07T23:36:36.479-0300] {task_command.py:426} INFO - Running <TaskInstance: preprocess_predict.preprocess manual__2024-10-08T02:36:35.215499+00:00 [running]> on host 4a07270c49a4
[2024-10-07T23:36:36.573-0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='preprocess_predict' AIRFLOW_CTX_TASK_ID='preprocess' AIRFLOW_CTX_EXECUTION_DATE='2024-10-08T02:36:35.215499+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-08T02:36:35.215499+00:00'
[2024-10-07T23:36:36.574-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-07T23:36:36.575-0300] {baseoperator.py:399} WARNING - PythonVirtualenvOperator.execute cannot be called outside TaskInstance!
[2024-10-07T23:36:36.577-0300] {process_utils.py:183} INFO - Executing cmd: /home/***/.local/bin/python -m virtualenv /tmp/venvli7n1yuw --python=python
[2024-10-07T23:36:36.578-0300] {process_utils.py:187} INFO - Output:
[2024-10-07T23:36:37.259-0300] {process_utils.py:191} INFO - created virtual environment CPython3.12.3.final.0-64 in 204ms
[2024-10-07T23:36:37.260-0300] {process_utils.py:191} INFO -   creator CPython3Posix(dest=/tmp/venvli7n1yuw, clear=False, no_vcs_ignore=False, global=False)
[2024-10-07T23:36:37.261-0300] {process_utils.py:191} INFO -   seeder FromAppData(download=False, pip=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-10-07T23:36:37.262-0300] {process_utils.py:191} INFO -     added seed packages: pip==24.2
[2024-10-07T23:36:37.264-0300] {process_utils.py:191} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-10-07T23:36:37.299-0300] {process_utils.py:183} INFO - Executing cmd: /tmp/venvli7n1yuw/bin/pip install -r /tmp/venvli7n1yuw/requirements.txt
[2024-10-07T23:36:37.300-0300] {process_utils.py:187} INFO - Output:
[2024-10-07T23:36:39.004-0300] {process_utils.py:191} INFO - Collecting joblib (from -r /tmp/venvli7n1yuw/requirements.txt (line 1))
[2024-10-07T23:36:39.006-0300] {process_utils.py:191} INFO -   Using cached joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
[2024-10-07T23:36:39.275-0300] {process_utils.py:191} INFO - Collecting numpy (from -r /tmp/venvli7n1yuw/requirements.txt (line 2))
[2024-10-07T23:36:39.277-0300] {process_utils.py:191} INFO -   Using cached numpy-2.1.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
[2024-10-07T23:36:39.484-0300] {process_utils.py:191} INFO - Collecting pandas (from -r /tmp/venvli7n1yuw/requirements.txt (line 3))
[2024-10-07T23:36:39.486-0300] {process_utils.py:191} INFO -   Using cached pandas-2.2.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (89 kB)
[2024-10-07T23:36:39.649-0300] {process_utils.py:191} INFO - Collecting scikit-learn (from -r /tmp/venvli7n1yuw/requirements.txt (line 4))
[2024-10-07T23:36:39.651-0300] {process_utils.py:191} INFO -   Using cached scikit_learn-1.5.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (13 kB)
[2024-10-07T23:36:39.696-0300] {process_utils.py:191} INFO - Collecting python-dateutil>=2.8.2 (from pandas->-r /tmp/venvli7n1yuw/requirements.txt (line 3))
[2024-10-07T23:36:39.698-0300] {process_utils.py:191} INFO -   Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
[2024-10-07T23:36:39.773-0300] {process_utils.py:191} INFO - Collecting pytz>=2020.1 (from pandas->-r /tmp/venvli7n1yuw/requirements.txt (line 3))
[2024-10-07T23:36:39.775-0300] {process_utils.py:191} INFO -   Using cached pytz-2024.2-py2.py3-none-any.whl.metadata (22 kB)
[2024-10-07T23:36:39.805-0300] {process_utils.py:191} INFO - Collecting tzdata>=2022.7 (from pandas->-r /tmp/venvli7n1yuw/requirements.txt (line 3))
[2024-10-07T23:36:39.807-0300] {process_utils.py:191} INFO -   Using cached tzdata-2024.2-py2.py3-none-any.whl.metadata (1.4 kB)
[2024-10-07T23:36:39.959-0300] {process_utils.py:191} INFO - Collecting scipy>=1.6.0 (from scikit-learn->-r /tmp/venvli7n1yuw/requirements.txt (line 4))
[2024-10-07T23:36:39.962-0300] {process_utils.py:191} INFO -   Using cached scipy-1.14.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
[2024-10-07T23:36:40.018-0300] {process_utils.py:191} INFO - Collecting threadpoolctl>=3.1.0 (from scikit-learn->-r /tmp/venvli7n1yuw/requirements.txt (line 4))
[2024-10-07T23:36:40.020-0300] {process_utils.py:191} INFO -   Using cached threadpoolctl-3.5.0-py3-none-any.whl.metadata (13 kB)
[2024-10-07T23:36:40.049-0300] {process_utils.py:191} INFO - Collecting six>=1.5 (from python-dateutil>=2.8.2->pandas->-r /tmp/venvli7n1yuw/requirements.txt (line 3))
[2024-10-07T23:36:40.051-0300] {process_utils.py:191} INFO -   Using cached six-1.16.0-py2.py3-none-any.whl.metadata (1.8 kB)
[2024-10-07T23:36:40.066-0300] {process_utils.py:191} INFO - Using cached joblib-1.4.2-py3-none-any.whl (301 kB)
[2024-10-07T23:36:40.068-0300] {process_utils.py:191} INFO - Using cached numpy-2.1.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.0 MB)
[2024-10-07T23:36:40.084-0300] {process_utils.py:191} INFO - Using cached pandas-2.2.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.7 MB)
[2024-10-07T23:36:40.098-0300] {process_utils.py:191} INFO - Using cached scikit_learn-1.5.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.9 MB)
[2024-10-07T23:36:40.111-0300] {process_utils.py:191} INFO - Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
[2024-10-07T23:36:40.113-0300] {process_utils.py:191} INFO - Using cached pytz-2024.2-py2.py3-none-any.whl (508 kB)
[2024-10-07T23:36:40.115-0300] {process_utils.py:191} INFO - Using cached scipy-1.14.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (40.8 MB)
[2024-10-07T23:36:40.155-0300] {process_utils.py:191} INFO - Using cached threadpoolctl-3.5.0-py3-none-any.whl (18 kB)
[2024-10-07T23:36:40.156-0300] {process_utils.py:191} INFO - Using cached tzdata-2024.2-py2.py3-none-any.whl (346 kB)
[2024-10-07T23:36:40.158-0300] {process_utils.py:191} INFO - Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
[2024-10-07T23:36:40.368-0300] {process_utils.py:191} INFO - Installing collected packages: pytz, tzdata, threadpoolctl, six, numpy, joblib, scipy, python-dateutil, scikit-learn, pandas
[2024-10-07T23:36:55.225-0300] {process_utils.py:191} INFO - Successfully installed joblib-1.4.2 numpy-2.1.2 pandas-2.2.3 python-dateutil-2.9.0.post0 pytz-2024.2 scikit-learn-1.5.2 scipy-1.14.1 six-1.16.0 threadpoolctl-3.5.0 tzdata-2024.2
[2024-10-07T23:36:55.645-0300] {process_utils.py:183} INFO - Executing cmd: /tmp/venvli7n1yuw/bin/python /tmp/venv-calle7o8_x2q/script.py /tmp/venv-calle7o8_x2q/script.in /tmp/venv-calle7o8_x2q/script.out /tmp/venv-calle7o8_x2q/string_args.txt /tmp/venv-calle7o8_x2q/termination.log
[2024-10-07T23:36:55.646-0300] {process_utils.py:187} INFO - Output:
[2024-10-07T23:36:55.742-0300] {process_utils.py:191} INFO - Traceback (most recent call last):
[2024-10-07T23:36:55.744-0300] {process_utils.py:191} INFO -   File "/tmp/venv-calle7o8_x2q/script.py", line 64, in <module>
[2024-10-07T23:36:55.745-0300] {process_utils.py:191} INFO -     res = task_preprocess(*arg_dict["args"], **arg_dict["kwargs"])
[2024-10-07T23:36:55.746-0300] {process_utils.py:191} INFO -           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-10-07T23:36:55.747-0300] {process_utils.py:191} INFO - TypeError: task_preprocess() missing 1 required positional argument: 'ti'
[2024-10-07T23:36:56.051-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-07T23:36:56.063-0300] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 437, in execute
    return super().execute(context=serializable_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 759, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 514, in _execute_python_callable_in_subprocess
    raise AirflowException(error_msg) from None
airflow.exceptions.AirflowException: Process returned non-zero exit status 1.
task_preprocess() missing 1 required positional argument: 'ti'
[2024-10-07T23:36:56.067-0300] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=preprocess_predict, task_id=preprocess, run_id=manual__2024-10-08T02:36:35.215499+00:00, execution_date=20241008T023635, start_date=20241008T023636, end_date=20241008T023656
[2024-10-07T23:36:56.085-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 94 for task preprocess (Process returned non-zero exit status 1.
task_preprocess() missing 1 required positional argument: 'ti'; 4259)
[2024-10-07T23:36:56.107-0300] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-07T23:36:56.123-0300] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-07T23:36:56.127-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
